apiVersion: apps/v1
kind: Deployment

metadata:
  name: ledger-api
  namespace: payments
  labels:
    app: ledger-api

spec:
  replicas: 3

  selector:
    matchLabels:
      app: ledger-api

  template:
    metadata:
      labels:
        app: ledger-api

    spec:
      serviceAccountName: ledger-api-sa

      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001

        seccompProfile:
          type: RuntimeDefault

      containers:
      - name: ledger-api

        image: yogeeshkv19/ledger-api:v1.0
        imagePullPolicy: Always

        ports:
        - containerPort: 8080

        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true

          capabilities:
            drop:
            - ALL


        envFrom:
        - configMapRef:
            name: ledger-api-config

        - secretRef:
            name: ledger-api-secret


        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"

          limits:
            cpu: "500m"
            memory: "512Mi"


        livenessProbe:
          httpGet:
            path: /health
            port: 8080

          initialDelaySeconds: 20
          periodSeconds: 10


        readinessProbe:
          httpGet:
            path: /health
            port: 8080

          initialDelaySeconds: 10
          periodSeconds: 5
