apiVersion: v1
kind: ServiceAccount
metadata:
  name: developer
  namespace: payments
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator
  namespace: payments
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin
  namespace: payments
