apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ledger-api-role
  namespace: payments

rules:
- apiGroups: [""]
  resources:
    - configmaps
  resourceNames:
    - ledger-api-config
  verbs:
    - get
