apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ledger-api-rolebinding
  namespace: payments

subjects:
- kind: ServiceAccount
  name: ledger-api-sa
  namespace: payments

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ledger-api-role
