---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ledger-api-secret
  namespace: payments
spec:
  encryptedData:
    DB_PASSWORD: AgAPs0tc0v3XL1MV0l2OJVdkGLZC4QI7klolvCggbQngdy70aU75zue8GNAryBLvl5HAVQ2PHCQ4GWffXauPnwmyAgxUnHwK7/j8dgKZZmy9MaBXcme9hIaZ4lFPFocTV7CmYffKGODrqdPGC9YQDYdI99+4ThBToVA+Lugx3pK/c1MB6c3WOUa3nOcQyvgnZoxMASybu4bAmz8XkkBDjuOK+qxmB3MqoOHTGHgPUho6k2aXTqPYgE0gGbnb3rGUYNJoTR8c3YUitpZPWbjYCk5rS69H2L3eeDeKU/Qh7H+Z5GyA9DQ1Tu5PAbiNhZR8IALLlFuoKeXjB/AMOb64NpGerJug6HXxHr5hXDFE2M+B/5MeG2eiuleewsMBivhhR+NlW4VKATgXxOHfkNxVeetLtig4V7deX7n38tk2qfGN9Ulab5j/1Ol9jdEunkUgbDGj9kBXBJTCG5fiBXfbPkIBb/SIadEosPbSYD8ta/dN1Sej304HYJjsh1PG/XXkTL8c3oWKfD5zGwcpOUYrclnKmXaEV3KwtwTkLGHLzWQheED58VMqwKzwUwlv+EkSXY1V3z7fj3v2jRnEUcmqWEVwT+iSo0oggTauB4EUCHqglfIpjSf6Ft79WWiIpMna2U2+ML1aso53D0yt0FU1LTby+cOdLOCGpdkH7iwr9yLw3BATjtWgQsYPwkss3OFvlQXl/waFyw6LVAkPjA==
    STRIPE_API_KEY: AgC4PMu0RF5w5HgL+EtiofomZ6ezJMCneZrXqz7IR2AOySpaL95GNWxcIOlDo47WOsgLzaZwyeeCsnofQK0VxzqS/TMPPz3G4V8vbpnxcW4Z1pM8vwE+9aMPYUZhd9O1vf0w8w76ruDZK7/SUgg8fiSnl9ttcuCh1xX8yYLvS8VIH9kqiOP4tg1eG9vEExx+PY3EWGPlKTNXjwg+A4ydpoL9qQ4HazqIXnaJLHYuZGypqhKJlQrTx1OgwZneeADo/uQIZ8KnIrWIujks3jqYUM/fKgSJR/XniTb7LzQvpUIdfTCBGvkpbG3DAB3pszKPRxvsAui+8PLMBjk3KDRppJyt8XAfwhQWx5Z0vjass8qc78EbbbIMH2PffaxHU381ScB18eoexBw2fChBhpY4Q/xjzEi6T1P9wUeWCG4BI9FXJIV5jbMpdj18cD4k6XbgBRvUIM1gqZ7DxdBcbWuK+NvxIfijEkUp/sIYbR1BDkV+Qx8AlY3ty37pCf80zKq+Jq5dCfYQL9aRpntnpniZs5QioVoW25DxRmiuszbiDSwJVgRLZGSPYL0TEVIfY6GSh9uZrqPeGl3MLIvPSSCMftWhy8BO2Oj4iu9eaLw7s9CHyVPzD7f1CgWslGGYpU/UdwHxvsX5GUd6MJngroVcr/fB/BrgawfnhYOym+Nk6BUe5hyipZYhIPeNvjOigiYx6iBAbjXEQGVCOd68O9oR700kOXmYJKqVRBfSnthXeg==
  template:
    metadata:
      name: ledger-api-secret
      namespace: payments
    type: Opaque

