apiVersion: ENC[AES256_GCM,data:a1M=,iv:rUl4gZUcZ5yXu3scVVyQhKdXnyNKulBJDLCFcW5YIfs=,tag:FQKhMgCqLBl0uOA5lPZRUg==,type:str]
kind: ENC[AES256_GCM,data:OhICtFWX,iv:q2Vzm/PvDiATakP2Nxd8b2dYpqByFbqtz+qWA9zLo50=,tag:frSISAPZqbP8F2075jjRWw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:cXXG6WZl4u/nPOQgDJb2WAg=,iv:NiAdYp6LM16zpEDkZnqtKu6vRQsyuUZhr3uIJzUsHZM=,tag:2MZ2viaN0ZwPcpQJCKeb1g==,type:str]
    namespace: ENC[AES256_GCM,data:knC68O8LKiU=,iv:EuHkJKSrRCvyVE/IdX11FYTxMnabkWIyTYjZmLiNoU0=,tag:AQLw4xvZm3D1EEJJ5siVwA==,type:str]
type: ENC[AES256_GCM,data:1BDO/k2T,iv:bYnA9jcXF2Z8ZZdGrUUbTTJ7JIAOpW1Bxc679uG9eBk=,tag:gflKCFt8vZVtuRkprdE7vQ==,type:str]
stringData:
    STRIPE_API_KEY: ENC[AES256_GCM,data:QMzbM7WJcPq2lkH+hQH/np/cdkns3JZQGDRe8GA=,iv:iyBkjDJcrdFbxybFcs2PPGTkJUSE2UAyjYzcIDF2t14=,tag:QtnoFaTefb9iHWAAqUtJWw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:5yqXH7Sy9Iqm81s=,iv:eiiag/7yps0IhTyZVrIsMWyrOmnH/f5EvlFWMNyCF8s=,tag:WgV9VGhh3p5Y3QW7DbxCiQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtV2Z4cDVHaS9TekpUc05Y
            c1BKOUxKemhjY0FxT0l1KzJJLzExTWQ1SVVVCkFNUmZldlR1dFYwQmxNVEY4d0J5
            ZktQZXFKczdreEl0bzFHWDd4TC9IYnMKLS0tIG5XYlU2MDZHcnFhejhNMW91SE1j
            clFMdE9QTVJzVzVzZUZJUWFlRnVvNVEKfs7yBOMtuZrAjiMl0k4M7hAMQzWUZh5i
            /DlStxMKX0Fkooa9grgPKocSBhvfy1ylfH9fcxChyzrx05F/bKs8KA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kld46c65rxkmwt78zlkgmrdglda2k6srqngfcmxtgxzx053ecyxs45jn74
    lastmodified: "2026-07-30T08:34:05Z"
    mac: ENC[AES256_GCM,data:JChXwpwpnsMsXk+7pkmpg3+dV4qe8odcdJDseiCpNNwlCWrzFMoZp5norChmVrsl+c0VAdlGNj7qkfvIZmqXgKyJ11eVlZeMHvUT/tjYmm9Reb/cAgvYw7R8857Tog1An2Yxef21ySiB/biGFVPd5gGfTTjrhu9Rmp1HA2hhiNI=,iv:+qjqzqw7O5zMFTJz5tS+KqXPSDhJXflHfAqu3CqN5Lg=,tag:zXG7cDdqmA8rG/71t1YNBg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
